use std::process::Command;

fn bin() -> Command {
    let exe = env!("CARGO_BIN_EXE_cargo-fastdev");
    Command::new(exe)
}

#[test]
fn cli_doctor_text_ok() {
    let out = bin().arg("doctor").output().unwrap();
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("Toolchain Status"));
}

#[test]
fn cli_doctor_json_ok() {
    let out = bin().args(["doctor", "--format", "json"]).output().unwrap();
    assert!(out.status.success());
    let s = String::from_utf8(out.stdout).unwrap();
    let v: serde_json::Value = serde_json::from_str(&s).unwrap();
    assert!(v.get("toolchain").is_some());
}

#[test]
fn cli_init_print_ok() {
    let out = bin().args(["init", "--print"]).output().unwrap();
    assert!(out.status.success());
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("Generated by cargo-fastdev"));
}

#[test]
fn cli_proxy_check_runs() {
    // We just verify the command executes; result depends on environment.
    // `cargo check` on the crate itself should be ok.
    let out = bin().args(["check"]).output().unwrap();
    assert!(out.status.success());
}
