# File: .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `cargo fastdev --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows / Linux / macOS"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual output
      render: text
    validations:
      required: true
